### ISSUE TITLE
Issue with WinReg -> Format for Mac?

### ISSUE THREAD

**Issue by day1dan** [RavenHustler/yelp-data-scraper#2]
Thank you @RavenHustler for putting this together! After trying a number of times to run this line, it keeps coming back with _"python setup.py egg_info” failed with error code 1_ I've deleted Python and reinstalled (v3.7) and deleted/reinstalled Pip (v.10.0.1) to no avail.

> UPDATE July 12, 2018: This error is preceded by this text:
> 
> > Complete output from command python setup.py egg_info:
> >     Traceback (most recent call last):
> >       File "<string>", line 1, in <module>
> >       File "/private/var/folders/rj/01wwzwmn1zd42s9jrnxxvm380000gn/T/pip-install-WWJ2fE/pypiwin32/setup.py", line 83, in <module>
> >         import _winreg
> >     ImportError: No module named _winreg
> 
> I'm running a Mac 10.13.6, Python 2.7, Pip 10.0.1

After scouring stackoverflow and other platforms for hours hours with no luck I figured I'd ask you. Any thoughts? Thanks!

**Comment by day1dan** [comment]
RESOLVED - SEE OTHER ISSUE: "No Module named yelp.settings" for resolution.
